name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0        # To fetch news from API
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  cupertino_icons: ^1.0.8
  # The following adds the Cupertino Icons font to your application.

  share_plus: ^12.0.0
  url_launcher: ^6.3.1
  file_picker: ^10.3.3
  image_picker: ^1.1.2
  fl_chart: ^1.1.1
  flutter_colorpicker: ^1.1.0
  open_file: ^3.2.1
  intl: ^0.17.0
  timeago: ^3.3.0

  # Google charts (still works with Flutter 3.7+)
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
      ref: master

flutter:
  uses-material-design: true

  assets:

    - assets/images/spacyn_logo.png
    - assets/images/Sp_logo.png
    - assets/images/post1.jpg
    - assets/images/post2.jpg
    - assets/images/post3.jpg
    - assets/images/profile.jpg

